apiVersion: batch/v1
kind: Job
metadata:
  name: upload-job
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: file-upload
        imagePullPolicy: Always
        image: ashbourne1990/azure-blob-storage-bigfile-upload:latest
        env:
        - name: ACCOUNT
          valueFrom:
            secretKeyRef:
              key: storage_account
              name: sa-secret-03
        - name: SAS_TOKEN
          valueFrom:
            secretKeyRef:
              key: sas_token
              name: sa-secret-03
        - name: CONTAINER
          valueFrom:
            secretKeyRef:
              key: container
              name: sa-secret-03
      restartPolicy: Never